---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bandanablue
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/wayblueorg/sway
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  # - type: akmods
  #   base: bazzite
  #   install:
  #     - common
  # - extra
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
  - type: dnf
    repos:
      copr:
        - atim/starship
        - atim/nushell
        - lihaohong/chezmoi
        - fmonteghetti/keyd
        - petersen/nix
    install:
      packages:
        # Normal
        - starship
        - nushell
        - chezmoi
        - neovim
        - kde-partitionmanager
        - tlp
        # KDE packages
        - dolphin
        - ark
        - gwenview
        - okular
        # Keyboard
        - fcitx5
        - fcitx5-mozc
        # Copr
        - keyd
        - nix

    group-install:
      packages:
        - virtualization
    remove:
      packages:
        - firefox
        - firefox-langpacks
  - type: systemd
    system:
      enabled:
        - keyd
        - tlp
      disabled:
        - flatpak-system-update.timer
    user:
      disabled:
        - flatpak-user-update.timer
  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
        - io.gitlab.librewolf-community
        - org.mozilla.firefox
        - org.freedesktop.Platform.ffmpeg-full
        - org.kde.krita
        - com.github.marhkb.Pods
        - com.github.tchx84.Flatseal
        - com.heroicgameslauncher.hgl
        - com.obsproject.Studio
        - com.spotify.Client
        - com.usebottles.bottles
        - dev.vencord.Vesktop
        - io.github.arunsivaramanneo.GPUViewer
        - io.missioncenter.MissionCenter
        - org.gnome.Snapshot
        - org.gnome.Solanum
        - org.gnome.clocks
        - org.kde.kdenlive
        - org.kde.kolourpaint
        - org.localsend.localsend_app
        - org.libreoffice.LibreOffice
      remove:
        - org.gnome.eog
    user: {} # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

  - type: bling
    install:
      - rpmfusion # install RPMFusion repos, including tainted repos & disable negativo17 repos if installed

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode # don't add spaces or "Nerd Font" suffix.
        - JetBrainsMono
        - NerdFontsSymbolsOnly
      google-fonts:
        - Roboto
        - Open Sans
