---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bandanablue
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/wayblueorg/sway
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  # - type: akmods
  #   base: bazzite
  #   install:
  #     - common
  # - extra
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
  - type: script
    snippets:
      - 'sh -c "$(curl -fsLS get.chezmoi.io)"'

  - type: dnf
    repos:
      copr:
        - atim/starship
        - atim/nushell
        - lihaohong/chezmoi
        - fmonteghetti/keyd
    install:
      packages:
        # Normal
        - starship
        - nushell
        - chezmoi
        - neovim
        - kde-partitionmanager
        - tlp
        # KDE packages
        - dolphin
        - ark
        - gwenview
        - okular
        # Keyboard
        - fcitx5
        - fcitx5-mozc
        - keyd

    group-install:
      packages:
        - virtualization
    remove:
      packages:
        - firefox
        - firefox-langpacks

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
        - io.gitlab.librewolf-community
        - org.mozilla.firefox
        - org.freedesktop.Platform.ffmpeg-full
      remove:
        - org.gnome.eog
    user: {} # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

  - type: bling
    install:
      - rpmfusion # install RPMFusion repos, including tainted repos & disable negativo17 repos if installed

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode # don't add spaces or "Nerd Font" suffix.
        - JetBrainsMono
        - NerdFontsSymbolsOnly
      google-fonts:
        - Roboto
        - Open Sans
  - type: yafti
    custom-flatpaks:
      - Celluloid: io.github.celluloid_player.Celluloid
      - Krita: org.kde.krita
      - Pods: com.github.marhkb.Pods
      - Flatseal: com.github.tchx84.Flatseal
      - hgl: com.heroicgameslauncher.hgl
      - Studio: com.obsproject.Studio
      - Client: com.spotify.Client
      - bottles: com.usebottles.bottles
      - Vesktop: dev.vencord.Vesktop
      - GPUViewer: io.github.arunsivaramanneo.GPUViewer
      - MissionCenter: io.missioncenter.MissionCenter
      - Snapshot: org.gnome.Snapshot
      - Solanum: org.gnome.Solanum
      - clocks: org.gnome.clocks
      - kdenlive: org.kde.kdenlive
      - kolourpaint: org.kde.kolourpaint
      - LibreOffice: org.libreoffice.LibreOffice
      - localsend_app: org.localsend.localsend_app
